CREATE TABLE REVIEW (
    REVIEW_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    WARD_ID INT NOT NULL,
    REVIEW_ENTRY VARCHAR(512),
    OVERALL DECIMAL(2, 1),
    ACTIVITIES DECIMAL(2, 1),
    FOOD DECIMAL(2, 1),
    BISHOP DECIMAL(2, 1),
    GENDER_RATIO DECIMAL(2, 1),
    LOCATION DECIMAL(2, 1),
    SPIRITUALITY DECIMAL(2, 1),
    LIKES INT,
    CREATED_DATE DATETIME NOT NULL,
    UPDATED_DATE DATETIME NOT NULL,    
    FOREIGN KEY (WARD_ID) REFERENCES WARD_ID(WARD_ID)
);